### PR TITLE
feat: use k6's new module API

### PR DESCRIPTION
**Pull request by olegbespalov**
# What?

Migrate the extension internals to the new k6's module API

# Why?

The old module API is deprecated and will be removed in the next release, which means that without the migration to a new API xk6-faker will stop building:

```
xk6 build master --output xk6-faker --with github.com/szkiba/xk6-faker
```

### CODE REVIEW

**Comment by colymore** [comment]
Time is here. Now is not possible to build without these changes.

**Comment by iwt-gabrielaoskroba** [comment]
@mstoykov is there a possibility to get this merged?

**Comment by mstoykov** [comment]
This is a question that should be asked to @szkiba . 

I am not a maintainer of this extension and have no rights to merge it.

**Comment by javaducky** [comment]
Hello @szkiba! There has been some interest in this extension. Would you be amicable to us forking and maintaining this repository from within the Grafana organization?

**Pull request merged**
